### ISSUE TITLE
Feat: support two view modes

### ISSUE THREAD

**Issue by dmytro-shchurov** [NikitchenkoSergey/scheme-designer#1]
In order to work with huge auditoriums (like stadiums or so) it would be helpful to render only sectors scheme at certain levels of zoom (at minimal ones).

**Comment by NikitchenkoSergey** [comment]
Now you can do it: 
add sector as object and render it by condition (scale, fo example), in place render function and click function also add this condition.
Thanks, I will think about optimize this proccess.

**Comment by dmytro-shchurov** [comment]
Thanks a lot. I've tried to setup a data schema so there are two object types: `Place` and `Sector`. 
At a beginning of their `renderFunction` `zoomManager.getScale()` value is taken and function exists immediately when scale exceeds or is less than a certain level (about 0.15).
After `schemeDesigner.render()` is called the first time after an initialization, the initial scale causes rendering only *sectors*.
When scale is small enough (big zoom), *places* begin to render.
So far everything looks good.

But when I zoom out then (back to smaller scale), whose places which were hovered by a mouse, are displayed when a canvas is dragged, and disappear when mouse is released. At the same time no `renderFunction` of those ghost places is called.
Browser Chrome v63.
Sector.renderFunction() looks like
```javascript
var renderSector = function (schemeObject, schemeDesigner, view) {
    var scale = schemeDesigner.getZoomManager().getScale();
    if (scale >= 0.15) {
        return;
    }

    var context = view.getContext();

    context.beginPath();

    var backgroundColor = '#' + schemeObject.params.backgroundColor;
    context.fillStyle = backgroundColor;
    context.strokeStyle = backgroundColor;

    var relativeX = schemeObject.getRelativeX(view);
    var relativeY = schemeObject.getRelativeY(view);

    var width = schemeObject.width;
    var height = schemeObject.height;
    context.rect(relativeX, relativeY, width, height);

    context.fill();
    context.stroke();
};
```

Sector data is quite simple (it does not matter whether sectors go at a beginning or at an end of the data file)
```json
{
        "ObjectName": "Sector",
        "ObjectType": "Sector",
        "Width": "2500",
        "Height": "500",
        "CX": "0.0",
        "CY": "0.0",
        "CX2": "2499",
        "CY2": "499",
        "Angle": "0.0",
        "cod_sec": "2",
        "Name_sec": "\u0410\u043c\u0444\u0438\u0442\u0435\u0430\u0442\u0440",
        "MinX": "0",
        "MinY": "0",
        "MaxX": "2500",
        "MaxY": "2500",
        "BackColor": "3300CC",
    },
    {
        "ObjectName": "Sector",
        "ObjectType": "Sector",
        "Width": "2500",
        "Height": "500",
        "CX": "0.0",
        "CY": "550.0",
        "CX2": "2499",
        "CY2": "1049",
        "Angle": "0.0",
        "cod_sec": "3",
        "Name_sec": "\u0410\u043c\u0444\u0438\u0442\u0435\u0430\u0442\u0440",
        "MinX": "0",
        "MinY": "0",
        "MaxX": "2500",
        "MaxY": "2500",
        "BackColor": "FF00CC",
    },
```

The problem can be partially solved by calling `schemeDesigner.updateCache(false)` in `schemeDesigner.zoom` event handler. But still some tiny side effects remain. Thus I think mouse events interractswith the cache in some unexpected way.

**Comment by NikitchenkoSergey** [comment]
Yes, problems with cache. You can disable it: set cacheSchemeRatio: false, in init params.
`options: {
            cacheSchemeRatio: false
        },`

**Comment by NikitchenkoSergey** [comment]
Layers supported from v1.1.0
