### ISSUE TITLE
How rerender scheme.

### ISSUE THREAD

**Issue by ZeroSOFAD** [NikitchenkoSergey/scheme-designer#11]
In the example there is a function "var clickOnPlace = function (schemeObject, schemeDesigner, view, e){". How in this function to call a rerender of the scheme.

This is necessary because of this function, I call my own Ajax function. And after returning from it, if you move the cursor over the place that was clicked, it is not selected.

var clickOnPlace = function (schemeObject, schemeDesigner, view, e){
   $.ajax({
       //.........
       success: function(data){
           // HOW IN THIS PLACE RERENDER SCHEME HALL ?
       }
   });
}

**Comment by NikitchenkoSergey** [comment]
for update cache:
schemeDesigner.updateCache(false)
for rerender scheme:
schemeDesigner.requestRenderAll()

https://github.com/NikitchenkoSergey/scheme-designer#api
