### ISSUE TITLE
Wrong selection when angle parameter is used for a schema object

### ISSUE THREAD

**Issue by dmytro-shchurov** [NikitchenkoSergey/scheme-designer#2]
Try to set `angle: 45` in a schema object configuration. The object is rendered correctly. But when mouse moves over the rotated object, few nearest objects are highlighted also.

**Comment by NikitchenkoSergey** [comment]
Fixed
https://github.com/NikitchenkoSergey/scheme-designer/commit/136d1f76ef02bb7c9a1bbe1c615ad57409eb5bb2#diff-4cd49c21a19d8ba2d846c2f5871df350R65
