### ISSUE TITLE
Feat: support background objects

### ISSUE THREAD

**Issue by dmytro-shchurov** [NikitchenkoSergey/scheme-designer#3]
It would be nice to define a background object with a schema and to support it with the storage.
In v1.0.0 it's possible to render another type of object in a different way, but there are three issues with this:
1. An order matters. We have to respect an order in which objects appear in the schema to display objects at desired "layer".
2. `storage.treeDepth` parameter dramatically changes a result. When it is greater than 1, overlapping side effects makes an idea of background objects almost impossible. The object transparency level is also affected.
3. When one object is behind another (a seat for instance), mouse hover events occur only when a pointer moves fast enough.

One of use cases is for example to use SVG structure or a simple image as a background object with `context.drawImage()`.

**Comment by NikitchenkoSergey** [comment]
Layers are implemented in v1.1.0
