### ISSUE TITLE
Feat: support "invisible" objects

### ISSUE THREAD

**Issue by dmytro-shchurov** [NikitchenkoSergey/scheme-designer#4]
It would be nice to return a visibility status from `render()` method, so not visible objects won't be a part of the tree. In v1.0.0 even if an object is not rendered, it is still available to be searched, and still captures all mouse events.

**Comment by NikitchenkoSergey** [comment]
Added property **active**  for SchemeObject. Not active object dont handle events. Layer has **active** property too.
