### ISSUE TITLE
Feat: support layers

### ISSUE THREAD

**Issue by dmytro-shchurov** [NikitchenkoSergey/scheme-designer#6]
Previously requested features (except background objects) I guess can be automatically implemented by introducing only one feature. Layers.
1. Layer must be supported in the schema definition.
2. It must be able to arrange layers in a special schema configuration section (or in another way).
3. Layer contains other objects of different types.
4. Layer can be visible or hidden. When it is hidden, all contained objects must not handle mouse events, must not be rendered, must not be searchable.
5. Layer can be active or inactive. When it is inactive, all contained objects must not handle mouse events. Are rendered.
6. Information about containing layer must be passed to `render()` method of an object, or must be easily retrieved in `render()` method.
7. It must be possible to change layer state by it's name/id. Re-render of a canvas must be triggered then.

Examples of the layers: auditorium schema (contains one background object), sectors (with or without background object), price categories (with or without background object), labels or legends, links, alarm directives, etc..

**Comment by NikitchenkoSergey** [comment]
Start work in branch "layers" https://github.com/NikitchenkoSergey/scheme-designer/tree/layers

**Comment by NikitchenkoSergey** [comment]
Base version of layouts complete. Also fix bug with opacity of big objects.
