### ISSUE TITLE
Hovered place from invisible layer remains visible on drag

### ISSUE THREAD

**Issue by dmytro-shchurov** [NikitchenkoSergey/scheme-designer#7]
How to reproduce: 
1. add few lines of code to `schemeDesigner.zoom` handler:
```javascript
var scale = schemeDesigner.getZoomManager().getScale();

schemeDesigner.getStorageManager().setLayerVisibility('background', scale < 0.15);
schemeDesigner.getStorageManager().setLayerVisibility('default', scale >= 0.15);
```
2. When places are visible, hover some one at a center of a canvas, so it appears hovered/highlighted
3. With a mouse wheel decrease a zoom level, but don't move a mouse, so the place remains hovered/highlighted until the 'default' layer hides, and 'background' layer appears.
4. Click at any place at the 'background' layer and start to move/drag the scheme.

That previously hovered/highlighted place will be rendered above visible 'background' layer during dragging.

**Comment by NikitchenkoSergey** [comment]
I reproduce this bug.
Also, setLayerVisibility need to be called only when changing the visibility of layers, because it call cache rerender.

**Comment by NikitchenkoSergey** [comment]
Fixed: https://github.com/NikitchenkoSergey/scheme-designer/commit/59144e85c4396f8642e354c1a92d830a2fe579b0
