### ISSUE TITLE
Examples are outdated because SchemeObject fields are now protected

### ISSUE THREAD

**Issue by dmytro-shchurov** [NikitchenkoSergey/scheme-designer#8]
`SchemeObject.x`, `SchemeObject.y`, `SchemeObject.width`, `SchemeObject.height` now can be obtained with `SchemeObject.getBoundingRect()`, but there is not way to access `SchemeObject.params`.
`params` can hold user's data, and an access must be provided somehow.
Example widely uses `SchemeObject` fields as public ones.

**Comment by NikitchenkoSergey** [comment]
added getters for x, y, width, height, params https://github.com/NikitchenkoSergey/scheme-designer/commit/9a360b9265d45bd3554de1ce6b62eae56e407ace
