### ISSUE TITLE
Typo errors in SchemeObject

### ISSUE THREAD

**Issue by dmytro-shchurov** [NikitchenkoSergey/scheme-designer#9]
SchemObject@207
`return this.clickFunction(this, Scheme, view, e);` 
must be 
`return this.clickFunction(this, schemeDesigner, view, e);`

SchemeObject@222
`return this.mouseOverFunction(this, Scheme, view, e);` 
must be 
`return this.mouseOverFunction(this, schemeDesigner, view, e);`

SchemeObject@237
`return this.mouseLeaveFunction(this, Scheme, view, e);` 
must be 
`return this.mouseLeaveFunction(this, schemeDesigner, view, e);`

**Comment by NikitchenkoSergey** [comment]
fixed https://github.com/NikitchenkoSergey/scheme-designer/commit/9f9f23c80ded72cee85913d332a12ebaa5b8731e
